//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXhibition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.exhibitinfo = new HashSet<exhibitinfo>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int EVID { get; set; }
        public int HID { get; set; }
        public string name { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
        public string venue { get; set; }
        public string image { get; set; }
        public string floorplanimg { get; set; }
        public string category { get; set; }
        public string eventinfo { get; set; }
        public string note { get; set; }
        public decimal ticketprice { get; set; }
        public bool verify { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
    
        public virtual hosts hosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exhibitinfo> exhibitinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
