//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXhibition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exhibitinfo
    {
        public int EVID { get; set; }
        public int EID { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public string boothnumber { get; set; }
        public string productinfo { get; set; }
        public string status { get; set; }
        public Nullable<bool> verify { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> reviewDateTime { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
    
        public virtual events events { get; set; }
        public virtual exhibitors exhibitors { get; set; }
    }
}
